version: "1"

automerge:
  enabled: true
  require_explicit_apply: true

dirs:
  "terraform/dev":
    tags: ["dev"]
    when_modified:
      file_patterns: ["**/*"]
      autoplan: true
      autoapply: false

apply_requirements:
  create_pending_apply_check: true
  checks:
    - tag_query: "dev"
      approved:
        enabled: true
        any_of: []
        any_of_count: 1
      merge_conflicts:
        enabled: true
      status_checks:
        enabled: true

hooks:
  all:
    pre:
      - type: env
        name: TF_VAR_image_tag
        cmd: ["sh", "-c", "git rev-parse HEAD"]
    post:
      - type: run
        run_on: failure
        cmd: ["$TERRATEAM_ROOT/terraform/scripts/fetch_logs.sh", "mindplex-dev-cluster", "mindplex-semantic-dev", "/ecs/mindplex-semantic-dev"]
        